[project]
name = "inksim"
version = "0.2.5"
description = "Interactive embroidery simulator"
authors = [{ name = "Tony Karnigen" }]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.12"
dependencies = [
    "numba",
    "numpy",
    "pystitch",
    "pyside6-essentials",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-qt",
]


[project.urls]
Homepage = "https://github.com/karnigen/inksim"
Repository = "https://github.com/karnigen/inksim.git"
Issues = "https://github.com/karnigen/inksim/issues"


[project.scripts]
inksim = "inksim.cli:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
