[project]
name = "inksim"
version = "0.2.9"
description = "Interactive embroidery simulator"
authors = [{ name = "InkSim contributors" }]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.12"
dependencies = [
    "numba",
    "numpy",
    "pystitch",
    "pyside6-essentials",
    # "pyside6-addons",
    "pyopengl",
    "tomli-w",
    "filelock",
]

[dependency-groups]
dev = [
    "pillow",
    "pytest",
    "pytest-qt",
    "scipy",
]


[project.urls]
Homepage = "https://github.com/oorteo/inksim"
Repository = "https://github.com/oorteo/inksim.git"
Issues = "https://github.com/oorteo/inksim/issues"


[project.scripts]
inksim = "inksim.cli:main"

[project.gui-scripts]
inksim-gui = "inksim.cli:main"

[tool.pytest.ini_options]
testpaths = ["tests"]


[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
